-- Exhibitions. Permanent displays have no end date; temporary shows are dated
-- so that "what's on now" queries have something realistic to work with.

INSERT INTO exhibitions (museum_id, title, description, start_date, end_date, image_url, permanent)
SELECT m.id, e.title, e.description, e.start_date, e.end_date, e.image_url, e.permanent
FROM museums m
JOIN (VALUES
 ('ateneum', 'Stories of Finnish Art',
  'The rebuilt permanent collection display, arranged as six chapters from the 1800s to the 1960s, with Schjerfbeck, Gallen-Kallela, Simberg and Edelfelt at its heart.',
  DATE '2023-04-14', NULL::date, NULL, true),
 ('ateneum', 'Northern Light: Nordic Painting 1880-1910',
  'Finnish, Swedish, Norwegian and Danish painters working through the long northern summer and the longer winter, shown together for the first time in a decade.',
  DATE '2026-05-22', DATE '2026-11-08', NULL, false),
 ('kiasma', 'ARS 26: Machines That Dream',
  'Kiasma''s flagship international survey returns with twenty-eight artists working at the edge of machine learning, robotics and generative sound.',
  DATE '2026-04-10', DATE '2027-01-17', NULL, false),
 ('kiasma', 'Kiasma Collections: Bodies of Water',
  'A collection hang built around the Baltic, shorelines and the politics of water, drawn entirely from Kiasma''s own holdings.',
  DATE '2026-02-06', DATE '2026-10-25', NULL, false),
 ('amos-rex', 'Field of Light',
  'A full-hall immersive installation across the underground galleries, responding to visitors'' movement with sound and projected light.',
  DATE '2026-06-03', DATE '2026-12-13', NULL, false),
 ('amos-rex', 'Sigurd Frosterus Collection',
  'The founding collection of European modernism that Amos Anderson''s museum inherited, shown in rotation in the smaller vaulted rooms.',
  DATE '2018-08-30', NULL::date, NULL, true),
 ('ham', 'Tove Jansson Frescoes',
  'The two monumental 1947 frescoes Jansson painted for the Helsinki City Hall canteen, now permanently installed in their own HAM gallery.',
  DATE '2015-09-25', NULL::date, NULL, true),
 ('ham', 'Public Works: Art in the Helsinki Metro',
  'Photographs, maquettes and archive film about the artworks commissioned for the metro network since 1982.',
  DATE '2026-08-14', DATE '2027-03-07', NULL, false),
 ('design-museum', 'Utopia Now: The Story of Finnish Design',
  'The permanent exhibition, running from 19th-century craft schools through Aalto, Franck and Marimekko to contemporary studios.',
  DATE '2020-01-01', NULL::date, NULL, true),
 ('design-museum', 'Marimekko: Printing the Century',
  'Eight decades of Marimekko screen printing, from Maija Isola''s Unikko to current collaborations, with the original print tables.',
  DATE '2026-09-11', DATE '2027-02-21', NULL, false),
 ('architecture-museum', 'Wood, Concrete, Snow',
  'How Finnish architects have built for a climate that spends half the year below freezing - drawings, models and building-site photography.',
  DATE '2026-03-20', DATE '2026-10-04', NULL, false),
 ('national-museum', 'The Story of Finland',
  'The main historical exhibition, from prehistory through Swedish and Russian rule to independence and the modern republic.',
  DATE '2000-07-01', NULL::date, NULL, true),
 ('national-museum', 'Treasure Troves',
  'The vault: silver hoards, medieval reliquaries, coin finds and the objects too fragile to keep on open display.',
  DATE '2019-05-01', NULL::date, NULL, true),
 ('helsinki-city-museum', 'Children''s Town',
  'A permanent hands-on floor where children run a 1930s shop, school and kitchen. Free, like the rest of the museum.',
  DATE '2016-05-13', NULL::date, NULL, true),
 ('helsinki-city-museum', 'Helsinki in 1966',
  'One year in the life of the city, reconstructed from photographs, home films, tram tickets and the municipal archive.',
  DATE '2026-07-02', DATE '2027-01-11', NULL, false),
 ('natural-history-museum', 'History of Life',
  'From the first cells to the Ice Age, including the dinosaur hall and the museum''s much-photographed blue whale skeleton.',
  DATE '2008-06-01', NULL::date, NULL, true),
 ('natural-history-museum', 'Finnish Nature',
  'Dioramas of Finland''s habitats, from the Baltic archipelago through boreal forest to the Lapland fells.',
  DATE '2008-06-01', NULL::date, NULL, true),
 ('photography-museum', 'Documenting the Thaw',
  'Nordic documentary photographers on melting winters, shifting coastlines and the communities living with them.',
  DATE '2026-08-21', DATE '2026-12-20', NULL, false),
 ('suomenlinna-museum', 'Suomenlinna: 250 Years',
  'The permanent introduction to the fortress island, from Swedish Sveaborg to the inhabited UNESCO site of today.',
  DATE '2012-05-01', NULL::date, NULL, true),
 ('technology-museum', 'Power and Water',
  'The old waterworks machinery in place, explaining how Helsinki got its drinking water and its electricity.',
  DATE '2014-01-01', NULL::date, NULL, true),
 ('sports-museum', 'Helsinki 1952',
  'The Olympic Games that put Finland on the postwar map, told through kit, film and the stadium itself.',
  DATE '2021-08-01', NULL::date, NULL, true),
 ('sinebrychoff', 'The Collector''s Rooms',
  'Paul and Fanny Sinebrychoff''s preserved period interiors, hung as the couple arranged them in the 1890s.',
  DATE '2010-01-01', NULL::date, NULL, true),
 ('theatre-museum', 'Backstage',
  'A permanent hands-on exhibition: work the lighting desk, try the costumes, stand on a built set.',
  DATE '2016-01-01', NULL::date, NULL, true),
 ('taidehalli', 'Young Artists 2026',
  'The triennial survey of artists under 35 working in Finland, filling all four top-lit halls.',
  DATE '2026-09-05', DATE '2026-11-29', NULL, false),
 ('didrichsen', 'Picasso and the Mediterranean',
  'Ceramics and works on paper from the Didrichsen collection, shown with loans from private Nordic holdings.',
  DATE '2026-05-15', DATE '2026-09-27', NULL, false),
 ('villa-gyllenberg', 'Schjerfbeck Close Up',
  'The Gyllenberg collection''s Helene Schjerfbeck paintings, rehung with conservation notes and X-ray studies.',
  DATE '2026-06-12', DATE '2027-01-31', NULL, false),
 ('seurasaari', 'Midsummer at Seurasaari',
  'The island''s open-air season: working farmsteads, folk music and the bonfire that draws the whole city in June.',
  DATE '2026-05-15', DATE '2026-09-15', NULL, false),
 ('observatory', 'Measuring the Sky',
  'The permanent display of Engel''s observatory: refractors, the meridian circle and Finland''s part in mapping the stars.',
  DATE '2012-06-01', NULL::date, NULL, true),
 ('botanic-garden-greenhouses', 'Ten Climates Under Glass',
  'The permanent greenhouse route from rainforest to desert, with the Victoria water lily pool at its centre.',
  DATE '1998-01-01', NULL::date, NULL, true),
 ('aalto-house', 'The Aalto House Guided Tour',
  'The only way to see the house: a 50-minute guided visit through the home, studio and garden, in Finnish or English.',
  DATE '2002-01-01', NULL::date, NULL, true),
 ('tram-museum', 'A Hundred Years of Green',
  'The permanent tram hall: horse trams, the 1950s Karia cars, driver''s cabs open to sit in, and the depot itself.',
  DATE '2015-01-01', NULL::date, NULL, true),
 ('mannerheim-museum', 'The Marshal''s Home',
  'The guided tour of the house as Mannerheim left it: the library, the trophies, the campaign furniture.',
  DATE '1951-06-01', NULL::date, NULL, true)
) AS e(slug, title, description, start_date, end_date, image_url, permanent) ON e.slug = m.slug;
